import Head from "next/head";
import { AppPropsWithLayout } from "@/app/interface/home-page.interface";
import { HomePageLayout } from "@/app/layout";

function MyApp({ Component, pageProps }: AppPropsWithLayout) {
  const getLayout = Component.getLayout ?? ((page) => page);
  return getLayout(
    <>
      <Head>
        <title>Course</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
          {Component.getLayout ? (
            <Component {...pageProps} />
          ) : (
            <HomePageLayout>
              <Component {...pageProps} />
            </HomePageLayout>
          )}
     
    </>
  );
}

export default MyApp;
